impl: full debug echos

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -uo pipefail
+set -uo pipefail # -Eeuo
 
 post_init_error() {
   curl -fsSLX POST "$API/init/error" -d '{"error":"runtime initialization failed"}'
@@ -17,9 +17,12 @@ PREP_ENV_VARS="$(paste -sd "," <<< "$(env)")"
 printf "env vars\n%s\nwasmtime version %s" "$(env)" "$(/opt/bin/wasmtime --version)"
 
 trap - EXIT
-set +u
+set +u # -Eeu
 
 while :; do
+
+  echo "DEBUG: getting next event"
+
   response="$(curl -fsSLD - "$API/invocation/next")"
   event="${response#*\\n\\n}"
   headers="${response%%\\n\\n*}"
@@ -28,11 +31,20 @@ while :; do
   trace_id="$(grep -ioP "(?<=Lambda-Runtime-Trace-Id: )([^[:space:]]*)" <<< "$headers")"
   request_id="$(grep -ioP "(?<=Lambda-Runtime-Aws-Request-Id: )([^[:space:]]*)" <<< "$headers")"
   context="{\"function_arn\":\"$function_arn\",\"deadline_ms\":\"$deadline_ms\",\"request_id\":\"$request_id\",\"trace_id\":\"$trace_id\"}"
+
+  echo "DEBUG: bout to invoke wasm"
+
   {
     # allow /tmp?
     if result="$(/opt/bin/wasmtime --disable-cache --env="$PREP_ENV_VARS,_x_amzn_trace_id=$trace_id" --invoke="$HANDLER" "$FILE" "$event" "$context" 2>&1 | grep -v "$WARNING")"; then
+
+      echo "DEBUG: invocation ok"
+
       curl -fsSLX POST "$API/invocation/$request_id/response" -d "$result"
     else
+
+      echo "DEBUG: invocation fail"
+
       curl -fsSLX POST "$API/invocation/$request_id/error" -d "$result"
     fi
   } &
